VueCalculator completed
js-tasks-ru/vue-20220809_ivan870 pull request #3
Opened 2022-08-18 04:44 UTC by Kvanarin

2022-08-18 04:44 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-08-19 10:19 UTC, ShGKme requested changes
Требуется убрать побочный эффект из вычисляемого свойства.

2022-08-19 10:19 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  },
Вычисляемое свойство ни в коем случае не должно иметь побочных эффектов. Не должно менять какие-то данные снаружи, а только возвращать вычисленное значение, которое в итоге и станет значением вычисляемого свойства.

Это вычисляемое свойство и возвращает результат вычисления (который будет лежать в `sample` свойстве), и одновременно сохраняет его в `result`.

Свойство `result` не нужно совсем. `sample` уже делает всю нужную работу, ответ уже находится в свойстве компонента `sample`.

Кроме того, часто считается плохой практикой делать присваивание в `return`, так как его легко спутать с сравнением `==`, а у функции получается двойная работа: https://eslint.org/docs/latest/rules/no-return-assign

2022-08-22 04:44 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-08-22 10:31 UTC, ShGKme approved these changes
Принято 👍

2022-08-22 10:31 UTC, merged